# Generated by Django 4.1.3 on 2022-12-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edmonblog_application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(default=200),
        ),
    ]
